In [3]:
import pandas as pd

#initial data
reviews = [
    "OMG!!! I can't believe the Students were RUNNING soooo fast 😲🏃🏃‍♂️...",
"Yesterday, they visited 3 different Universities, Colleges & Institutes!!!",
"The PROFESSORS were teaching Machine-Learning, AI, and Data-Science; amazingly :)",
"Some students were coding, debugging, fixing ERRORS, and testing applications...",    
"Meanwhile, others were reading BOOKS 📚, writing NOTES!!!, and discussing projects???",
"The technologies included Python, Java, C++, JavaScript, React.js, and Node.js!!!",
"Finally, everyone said, 'We're learning better, faster, and smarter than ever before!!!' 🚀🔥"
]

#convert to dataframe
df_reviews = pd.DataFrame(reviews, columns=["Review"])
#convert to lowercase
df_reviews["Lowercase_reviews"] = df_reviews["Review"].str.lower()
#print
df_reviews

,Review,Lowercase_reviews
0,OMG!!! I can't believe the Students were RUNNI...,omg!!! i can't believe the students were runni...
1,"Yesterday, they visited 3 different Universiti...","yesterday, they visited 3 different universiti..."
2,"The PROFESSORS were teaching Machine-Learning,...","the professors were teaching machine-learning,..."
3,"Some students were coding, debugging, fixing E...","some students were coding, debugging, fixing e..."
4,"Meanwhile, others were reading BOOKS 📚, writin...","meanwhile, others were reading books 📚, writin..."
5,"The technologies included Python, Java, C++, J...","the technologies included python, java, c++, j..."
6,"Finally, everyone said, 'We're learning better...","finally, everyone said, 'we're learning better..."

Removing punctuations and emojis

In [4]:
import re
df_reviews["Review_noPunct"] = df_reviews["Lowercase_reviews"].apply(lambda x: re.sub(r'[^\w\s]', '', x))
df_reviews

,Review,Lowercase_reviews,Review_noPunct
0,OMG!!! I can't believe the Students were RUNNI...,omg!!! i can't believe the students were runni...,omg i cant believe the students were running s...
1,"Yesterday, they visited 3 different Universiti...","yesterday, they visited 3 different universiti...",yesterday they visited 3 different universitie...
2,"The PROFESSORS were teaching Machine-Learning,...","the professors were teaching machine-learning,...",the professors were teaching machinelearning a...
3,"Some students were coding, debugging, fixing E...","some students were coding, debugging, fixing e...",some students were coding debugging fixing err...
4,"Meanwhile, others were reading BOOKS 📚, writin...","meanwhile, others were reading books 📚, writin...",meanwhile others were reading books writing n...
5,"The technologies included Python, Java, C++, J...","the technologies included python, java, c++, j...",the technologies included python java c javasc...
6,"Finally, everyone said, 'We're learning better...","finally, everyone said, 'we're learning better...",finally everyone said were learning better fas...

Remove stopwords for that take the nltk lib for corpus of the stopwords

In [12]:


# import nltk
# from nltk.corpus import stopwords

# nltk.download('stopwords')

# stop_words = set(stopwords.words('english'))

stop_words = {
    "a", "an", "the", "is", "are", "was", "were",
    "in", "on", "at", "of", "to", "for", "and",
    "or", "but", "with", "by"
}
df_reviews["No_Stopwords"] = df_reviews["Review_noPunct"].apply(lambda x: ' '.join(word for word in x.split() if x not in stop_words))

df_reviews

,Review,Lowercase_reviews,Review_noPunct,No_Stopwords
0,OMG!!! I can't believe the Students were RUNNI...,omg!!! i can't believe the students were runni...,omg i cant believe the students were running s...,omg i cant believe the students were running s...
1,"Yesterday, they visited 3 different Universiti...","yesterday, they visited 3 different universiti...",yesterday they visited 3 different universitie...,yesterday they visited 3 different universitie...
2,"The PROFESSORS were teaching Machine-Learning,...","the professors were teaching machine-learning,...",the professors were teaching machinelearning a...,the professors were teaching machinelearning a...
3,"Some students were coding, debugging, fixing E...","some students were coding, debugging, fixing e...",some students were coding debugging fixing err...,some students were coding debugging fixing err...
4,"Meanwhile, others were reading BOOKS 📚, writin...","meanwhile, others were reading books 📚, writin...",meanwhile others were reading books writing n...,meanwhile others were reading books writing no...
5,"The technologies included Python, Java, C++, J...","the technologies included python, java, c++, j...",the technologies included python java c javasc...,the technologies included python java c javasc...
6,"Finally, everyone said, 'We're learning better...","finally, everyone said, 'we're learning better...",finally everyone said were learning better fas...,finally everyone said were learning better fas...

Lemmatisation

In [16]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

df_reviews["Stemmed_reviews"] = df_reviews["No_Stopwords"].apply(lambda x: ' '.join(ps.stem(word) for word in x.split()))

df_reviews

,Review,Lowercase_reviews,Review_noPunct,No_Stopwords,Stemmed_reviews,stemmed_reviews
0,OMG!!! I can't believe the Students were RUNNI...,omg!!! i can't believe the students were runni...,omg i cant believe the students were running s...,omg i cant believe the students were running s...,omg i cant believ the student were run soooo fast,omg i cant believ the student were run soooo fast
1,"Yesterday, they visited 3 different Universiti...","yesterday, they visited 3 different universiti...",yesterday they visited 3 different universitie...,yesterday they visited 3 different universitie...,yesterday they visit 3 differ univers colleg i...,yesterday they visit 3 differ univers colleg i...
2,"The PROFESSORS were teaching Machine-Learning,...","the professors were teaching machine-learning,...",the professors were teaching machinelearning a...,the professors were teaching machinelearning a...,the professor were teach machinelearn ai and d...,the professor were teach machinelearn ai and d...
3,"Some students were coding, debugging, fixing E...","some students were coding, debugging, fixing e...",some students were coding debugging fixing err...,some students were coding debugging fixing err...,some student were code debug fix error and tes...,some student were code debug fix error and tes...
4,"Meanwhile, others were reading BOOKS 📚, writin...","meanwhile, others were reading books 📚, writin...",meanwhile others were reading books writing n...,meanwhile others were reading books writing no...,meanwhil other were read book write note and d...,meanwhil other were read book write note and d...
5,"The technologies included Python, Java, C++, J...","the technologies included python, java, c++, j...",the technologies included python java c javasc...,the technologies included python java c javasc...,the technolog includ python java c javascript ...,the technolog includ python java c javascript ...
6,"Finally, everyone said, 'We're learning better...","finally, everyone said, 'we're learning better...",finally everyone said were learning better fas...,finally everyone said were learning better fas...,final everyon said were learn better faster an...,final everyon said were learn better faster an...